name: Android CI

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Unit and Instrumentation Tests
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      ANDROID_HOME: ${{ runner.tool_cache }}/android-sdk
      PATH: $ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:/usr/local/bin:$PATH

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools: 31.0.0
          target: android-31

      - name: Install Dependencies
        run: ./gradlew dependencies --stacktrace

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Run Instrumentation Tests
        run: |
          adb devices
          ./gradlew connectedAndroidTest --stacktrace

      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: app/build/test-results/testDebugUnitTest/*.xml
          reporter: junit
          fail-on-error: false
          check-name: "Unit Test Results"
          comment: true

      - name: Publish Instrumentation Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Instrumentation Tests
          path: app/build/outputs/androidTest-results/connected/*.xml
          reporter: junit
          fail-on-error: false
          check-name: "Instrumentation Test Results"
          comment: true
