name: Plugin Test

on:
  push:
    branches:
      - main  # Or your main branch name
  pull_request:  # Run for pull requests as well
    branches:
      - main  # Or your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'               # Specify Java version
          distribution: 'temurin'           # Specify the JDK distribution
          cache: 'gradle'                   # Cache Gradle dependencies

      - name: Verify Gradle Wrapper
        run: |
          if [ ! -f ./gradlew ]; then
            echo "Gradle wrapper not found! Please add it to your repository."
            exit 1
          fi

      - name: Run plugin task
        run: ./gradlew greet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number || '' }}  # Empty if not a PR

      # Optional: Post Test Results to PR (only for pull requests)
      - name: Post Test Results to PR (only for pull requests)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Posting test results for PR #${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
